source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin

"处理文本中显示乱码 start
set fenc=utf-8
set encoding=utf-8
set fileencodings=utf-8,ucs-bom,gb18030,gbk,gb2312,cp936,latin-1
set fileformat=dos

if has("win32")
set fileencoding=utf-8
else
set fileencoding=utf-8
endif
"处理文本中显示乱码 end

source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim
"处理consle输出乱码
language messages zh_CN.UTF-8
"中文乱码结束

" 另外一种解决中文乱码的方法
" set fileencodings=utf-8,ucs-bom,gb18030,gbk,gb2312,cp936
" set termencoding=utf-8
" set encoding=utf-8
" set fileencoding=utf-8

" 显示文件编码类型
set statusline=%<%F%h%m%r\ [%{&ff}]\ (%{strftime(\"%H:%M\ %d/%m/%Y\",getftime(expand(\"%:p\")))})%=%l,%c%V\ %h%m%r%=%{\"[\".(&fenc==\"\"?&enc:&fenc).((exists(\"+bomb\")\ &&\ &bomb)?\",B\":\"\").\"]\ \"}%k\ %P

set nocompatible             " 关闭 vi 兼容模式
filetype on
syntax on
color dracula
language messages zh_CN.UTF-8

set autochdir
set guifont=Consolas:h14     " 设置字体
set lines=30 columns=85
set nobackup
set noundofile
set confirm
set history=100
set showcmd
set incsearch
set ignorecase smartcase
set hlsearch
set smartindent
set autoindent
set shiftwidth=2
set tabstop=2
set expandtab
set showmatch
set laststatus=2
set noerrorbells
set novisualbell
set number
set nobomb
set guioptions-=T

let do_syntax_sel_menu = 1|runtime! synmenu.vim|aunmenu &Syntax

set diffexpr=MyDiff()
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      if empty(&shellxquote)
        let l:shxq_sav = ''
        set shellxquote&
      endif
      let cmd = '"' . $VIMRUNTIME . '\diff"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3
  if exists('l:shxq_sav')
    let &shellxquote=l:shxq_sav
  endif
endfunction
